apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-node-labels
  name: node-labels.yaml
  annotations:
    description.kpt.dev: Node labels fragment
    config.kubernetes.io/local-config: "true"
data:
  node-label:
    - node.kubernetes.io/instance-role=${cluster-node-name} # kpt-set: node.kubernetes.io/instance-name=${cluster-node-name}
    - node.kubernetes.io/instance-kind=${cluster-node-kind} # kpt-set: node.kubernetes.io/instance-kind=${cluster-node-kind}
    