apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-etcd
  name: etcd.yaml
  annotations:
    description.kpt.dev: Etcd settings fragment
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-etcd'
data:
  etcd-expose-metrics: true
  node-name: ${cluster-name}-${node-kind}-node # kpt-set: ${cluster-name}-${node-kind}-node
  with-node-id: false
