apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-cidrs
  name: cidrs.yaml
  annotations:
    description.kpt.dev: Network CIDRs fragment
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-cidrs'
data:
  cluster-cidr: ${cluster-pod-cider} # kpt-set: ${cluster-pod-cider}
  cluster-service-cidr: ${cluster-service-cidr} # kpt-set: ${cluster-service-cidr}
  kube-controller-manager-arg:
    - node-cidr-mask-size-ipv4=24
