apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /rke2-tls-san
  name: tls-san.yaml
  annotations:
    description.kpt.dev: TLS SAN fragment
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|rke2-tls-san'
data:
  tls-san:
    - localhost
    - gateway
    - 0.0.0.0
    - 127.0.0.1
    - ${cluster-vip-gateway-inetaddr} # kpt-set: ${cluster-vip-gateway-inetaddr}
    - ${cluster-node-gateway-inetaddr} # kpt-set: ${cluster-node-gateway-inetaddr}
    - ${cluster-node-host-inetaddr} # kpt-set: ${cluster-node-host-inetaddr}
